error: Fix formatting by removig trailing spaces
There's currently a line break at this point due to extraneous trailing spaces:

> Noticing and explicitly managing those errors `<br>`
> saves the rest of the program from various pitfalls.

See http://rustbyexample.com/error.html